spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/jvm-spring-mvc-jdbc
    username: dev
    password: dev
  database:
    driverClassName: org.postgresql.Driver
server:
  port: 8080